SELECT * FROM GENRE g ;
INSERT INTO GENRE VALUES ('CO', '코미디');
INSERT INTO GENRE VALUES ('TH', '스릴러');
INSERT INTO GENRE VALUES ('HO', '공포(호러)');
INSERT INTO GENRE VALUES ('FA', '가족');
INSERT INTO GENRE VALUES ('SF', 'SF');
INSERT INTO GENRE VALUES ('AC', '액션');
INSERT INTO GENRE VALUES ('WA', '전쟁');
INSERT INTO GENRE VALUES ('RO', '로맨스');
INSERT INTO GENRE VALUES ('DR', '드라마');
INSERT INTO GENRE VALUES ('MI', '미스터리');
INSERT INTO GENRE VALUES ('MA', '무협');
INSERT INTO GENRE VALUES ('AL', '성인물');
INSERT INTO GENRE VALUES ('AN', '애니메이션');
INSERT INTO GENRE VALUES ('CR', '범죄');
INSERT INTO GENRE VALUES ('WE', '서부극');
INSERT INTO GENRE VALUES ('HI', '사극');
INSERT INTO GENRE VALUES ('FN', '판타지');
INSERT INTO GENRE VALUES ('DO', '다큐멘터리');
INSERT INTO GENRE VALUES ('AD', '어드벤처');
INSERT INTO GENRE VALUES ('ET', '기타');

SELECT * FROM MOVIE_GRADE mg ;
INSERT INTO MOVIE_GRADE VALUES ('전체 관람가');
INSERT INTO MOVIE_GRADE VALUES ('12세 관람가');
INSERT INTO MOVIE_GRADE VALUES ('15세 관람가');
INSERT INTO MOVIE_GRADE VALUES ('청소년 관람불가');

SELECT * FROM movie_type;
INSERT INTO MOVIE_TYPE VALUES ('DU2D', '더빙/2D');
INSERT INTO MOVIE_TYPE VALUES ('DU3D', '더빙/3D');
INSERT INTO MOVIE_TYPE VALUES ('DE2D', '자막/2D');
INSERT INTO MOVIE_TYPE VALUES ('DE3D', '자막/3D');
INSERT INTO MOVIE_TYPE VALUES ('NO2D', '없음/2D');
INSERT INTO MOVIE_TYPE VALUES ('NO3D', '없음/3D');

SELECT * FROM loc;
INSERT INTO loc VALUES ('서울');
INSERT INTO loc VALUES ('경기');
INSERT INTO loc VALUES ('강원');
INSERT INTO loc VALUES ('대전/충청');
INSERT INTO loc VALUES ('부산/대구/경상');
INSERT INTO loc VALUES ('광주/전라');
INSERT INTO loc VALUES ('제주');

